### ISSUE TITLE
can't install the environment

### ISSUE THREAD

**Issue by hbaniecki** [Henrymachiyu/ProtoViT#1]
Hi, neither `pip install -r requirements.txt` (error: file uses `=` instead of `==`) nor `conda create --name test --file requirements.txt` (error: wrong `pypi_0` channels) work for me to install the environment.

**Comment by Henrymachiyu** [comment]
To reproduce the environment, only the packages specified in the README (such as timm, pytorch, augmentor, and cv2) are necessary. If you encounter issues with the environment setup, ensure that the PyTorch version is compatible with your system. Note that CUDA-related packages may also cause installation conflicts. Please use the requirements.txt file only as a reference, and install the specified packages manually to build the environment. Based on our test runs, the reproducibility of our work should be independent to pytorch and cuda versions.  It only depends on the version of timm, since different version of timm implements ViT in a slightly different way. 

I will leave this issue always open, in case someone has the same problem.

**Comment by gyzxla** [comment]
我在使用过程中遇到了以下的问题

**Comment by gyzxla** [comment]
我在使用中遇到了一些问题，我询问chatgpt后给了我修改方案Traceback (most recent call last):
  File "main.py", line 221, in <module>
    push_greedy.push_prototypes(
  File "/mnt/ProtoViT-main/push_greedy.py", line 275, in push_prototypes
    update_prototypes_on_batch(search_batch_input,
  File "/mnt/ProtoViT-main/push_greedy.py", line 97, in update_prototypes_on_batch
    slots_torch = torch.round(slots_torch_raw, decimals=1)# remove the case such as 1e-4, 1e-5 thats approximately 0
TypeError: round() got an unexpected keyword argument 'decimals'

**Comment by gyzxla** [comment]
我在使用中遇到了一些问题，我询问chatgpt后给了我修改方案，我不确定是否是代码的问题还是环境的问题
Traceback （最近调用最后）：
文件 “main.py”， 第 221 行， in
push_greedy.push_prototypes（
文件 “/mnt/ProtoViT-main/push_greedy.py”， 第 275 行， in
push_prototypes update_prototypes_on_batch（search_batch_input，
文件 “/mnt/ProtoViT-main/push_greedy.py”， 第 97 行， in
update_prototypes_on_batch slots_torch = torch.round（slots_torch_raw， decimals=1）# 删除 1e-4， 1e-5 等大约为 0 的大小写
TypeError： round（） got an unexpected keyword argument 'decimals'

Traceback (most recent call last):
  File "main.py", line 191, in <module>
    _, train_loss = tnt.train(model=ppnet, dataloader=train_loader, optimizer=warm_optimizer,
  File "/data/kb/hty/ProtoVit/train_and_test.py", line 245, in train
    return _train_or_test(model=model, dataloader=dataloader, optimizer=optimizer,
  File "/data/kb/hty/ProtoVit/train_and_test.py", line 141, in _train_or_test
    dist_init = torch.concat((dist_init, cos_jk.unsqueeze(-1)), dim = -1)
AttributeError: module 'torch' has no attribute 'concat'

Traceback (most recent call last):
  File "main.py", line 221, in <module>
    push_greedy.push_prototypes(
  File "/mnt/ProtoViT-main/push_greedy.py", line 275, in push_prototypes
    update_prototypes_on_batch(search_batch_input,
  File "/mnt/ProtoViT-main/push_greedy.py", line 97, in update_prototypes_on_batch
    slots_torch = torch.round(slots_torch_raw, decimals=1)# remove the case such as 1e-4, 1e-5 thats approximately 0
TypeError: round() got an unexpected keyword argument 'decimals'

Traceback (most recent call last):
  File "main.py", line 221, in <module>
    push_greedy.push_prototypes(
  File "/mnt/ProtoViT-main/push_greedy.py", line 293, in push_prototypes
    unique_elements, counts = torch.unique(slots_pushed, return_counts=True)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/_jit_internal.py", line 267, in fn
    return if_false(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/_jit_internal.py", line 265, in fn
    return if_true(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/functional.py", line 756, in _return_counts
    output, _, counts = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/functional.py", line 678, in _unique_impl
    output, inverse_indices, counts = torch._unique2(
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch.

Traceback (most recent call last):
  File "main.py", line 221, in <module>
    push_greedy.push_prototypes(
  File "/data/kb/hty/ProtoVit/push_greedy.py", line 239, in push_prototypes
    result_tensor = torch.where(slots_rounded == 0, torch.tensor(-1), slots_rounded)*200 # ensure extreme values for eval
RuntimeError: Expected condition, x and y to be on the same device, but condition is on cuda:0 and x and y are on cpu and cuda:0 respectively

**Comment by Henrymachiyu** [comment]
代码没有问题 我自己已经测过10几遍了 建议检查自己改动的地方以及适当的阅读代码和理解每一行在做什么。不知道你都做了什么改动以及chatgpt的推荐，没有办法帮你debug的。目前说的什么x,y没有在同一个device上。如果是 torch round的问题，可以检查一下torch 版本。从现有的bug上看，你的torch应该有一些问题，建议根据torch官网来安装。

顺便不推荐用chatgpt debug。
